export {Price} from './Price';
export {NavBar} from './NavBar';
export {TitleEvent} from './TitleEvent';
export {ContainerDetailsEvent} from './ContainerDetailsEvent'
export {EventDetails} from './EventDetails'
export {PurchaseTicketsBtn} from './PurchaseTicketsBtn'
export {EventInfo} from './EventInfo'
export {Location} from './Location'
export {Heading} from './Heading';